### ISSUE TITLE
a bug in SRModel.py

### ISSUE THREAD

**Issue by ChassWind** [aselsan-research-imaging-team/bicubic-plusplus#1]
i think the code
`self.conv_out = nn.Conv2d(32, (2*sr_rate)**2 * sr_rate, kernel_size=3, padding=1, bias=False)`
should be change as behind
`self.conv_out = nn.Conv2d(32, (2*sr_rate)**2 * 3, kernel_size=3, padding=1, bias=False)`
so that it not only can run in X3 but also can run in other upsample factor

**Comment by aselsan-research-imaging-team** [comment]
You're right, thanks, the file is updated accordingly.
